[package]
name = "server"
version = "0.1.0"
authors = ["Andrew Palmer"]

[dependencies]
bytes = "0.4"
futures = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-proto = "0.1"
tokio-service = "0.1"
serde = "1.0"
serde_derive = "1.0"
bincode = "0.8"
